apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-ui-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.kafkaUi.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
{{- end }}
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUi.image }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka:29092
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: zookeeper:2181
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /kafka-ui
            - name: KAFKA_UI_CONFIG_BASE_PATH
              value: /kafka-ui
          volumeMounts:
            - mountPath: /var/lib/kafka-ui/data
              name: data
          resources:
{{- if .Values.kafkaUi.resources }}
{{ toYaml .Values.kafkaUi.resources | nindent 12 }}
{{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kafka-ui-data
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kafka-ui
