apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renderer-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.renderer.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renderer
  template:
    metadata:
      labels:
        app: renderer
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
{{- end }}
      containers:
        - name: renderer
          image: {{ .Values.renderer.image }}
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: GF_RENDERING_SERVER_URL
              value: http://renderer:8081/render
            - name: GF_RENDERING_CALLBACK_URL
              value: http://grafana:3000/
            - name: GF_RENDERING_CHROME_PATH
              value: /usr/bin/chromium-browser
            - name: GF_RENDERING_CHROME_DISABLE_GPU
              value: "true"
            - name: GF_RENDERING_CHROME_NO_SANDBOX
              value: "true"
            - name: GF_RENDERING_CHROME_ENABLE_PRINT_BACKGROUND
              value: "true"
            - name: GF_RENDERING_CHROME_HEADLESS
              value: "true"
          volumeMounts:
            - mountPath: /tmp/render
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: renderer-data
---
apiVersion: v1
kind: Service
metadata:
  name: renderer
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: renderer
